module.exports = {
  View: 'View',
  Text: 'Text',
  TouchableOpacity: 'TouchableOpacity',
  StyleSheet: { create: (s) => s },
  Platform: { OS: 'android', select: (obj) => obj.android || obj.default },
  Dimensions: { get: () => ({ width: 375, height: 812 }) },
  ScrollView: 'ScrollView',
  TextInput: 'TextInput',
  ActivityIndicator: 'ActivityIndicator',
  Alert: { alert: jest.fn() },
  RefreshControl: 'RefreshControl',
  KeyboardAvoidingView: 'KeyboardAvoidingView',
  Image: 'Image',
  Linking: { openURL: jest.fn() },
  FlatList: 'FlatList',
  Switch: 'Switch',
  Modal: 'Modal',
};
